services:
  db:
    image: postgres:16-alpine
    container_name: sessionflow_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sessionflow
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: